### ISSUE TITLE
Binary negation is "negated" by the compiler

### ISSUE THREAD

**Issue by InsomniaKitten** [Daomephsta/unpick#3]
When code using binary negation `~` is compiled, the compiler replaces it with a literal representing the negated result of the right hand literal of the operation. This makes this trickier for constant unpicking when a constant is used in a binary negation, as the value differs when decompiled.

For example, the following code,
```java
public static final int FOO = 0b1;

public void setFoo(final boolean foo) {
  if (foo) {
    this.setFlags(this.getFlags() | FOO);
  else {
    this.setFlags(this.getFlags() & ~FOO);
  }
}
```
Would decompile to:
```java
public void setFoo(final boolean foo) {
  if (foo) {
    this.setFlags(this.getFlags() | 1);
  else {
    this.setFlags(this.getFlags() & -2);
  }
}
```
Ideally an unpick here would need to also target `-2` and represent it as `~FOO` but there is currently no way to declare a binary negation of the constant.

**Comment by Daomephsta** [comment]
As of 2f3002, cases like
`this.setFlags(this.getFlags() & ~FOO)`
`this.setFlags(this.getFlags() & ~FOO | BAR)`
should work

I'm still trying to figure out cases like
`this.setFlags(this.getFlags() & ~(FOO | BAR)`
I think I know how to handle them, but I get the feeling there's a gotcha somewhere.

**Comment by Daomephsta** [comment]
There was no gotcha, ef08d76067928adcfbfd81c0cc00a5d378cb3923 should close this.
